name: soti_schema
description: A powerful tool for generating schemas from Dart data classes, enabling seamless integration with AI models and data validation systems.
version: 1.0.0
homepage: https://github.com/shtse8/SotiSchema
repository: https://github.com/shtse8/SotiSchema

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  meta: ^1.15.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
